{
  "name": "chained-promises-catching-errors",
  "version": "1.0.0",
  "description": "In this example, 4 tasks are chained to fetch a random image from https://picsum.photos, validate its size and, if the size is smaller than 6KB, display it. Otherwise, or in case of an error, catch the promise rejection and show an error message.",
  "main": "index.html",
  "scripts": {
    "start": "parcel index.html --open",
    "build": "parcel build index.html"
  },
  "dependencies": {},
  "devDependencies": {
    "@babel/core": "7.2.0",
    "parcel-bundler": "^1.6.1"
  },
  "keywords": [
    "javascript",
    "promise",
    "promises",
    "promise chain",
    "then",
    "catch",
    "error catching",
    "error handling"
  ]
}